"""
Character executor for Phase 5.1: Robust Character Coordination.

``CharacterExecutor`` encapsulates a single character's LLM call + tool loop,
extracted from ``ConversationManager._handle_phase45_multi_character()`` and
``ConversationManager._execute_deferred_tasks()``.

The key Phase 5.1 addition is interception of the ``request_handoff`` tool
call: rather than executing it as a regular tool, the executor captures the
arguments as a ``handoff_signal`` and does NOT add a tool result for that
call, preventing a second tool-result round-trip to the LLM.
"""

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from models.message import ConversationContext

logger = logging.getLogger(__name__)

# Name of the special handoff tool that characters call to signal a handoff.
_HANDOFF_TOOL_NAME = "request_handoff"


@dataclass
class CharacterResponse:
    """
    The outcome of a single ``CharacterExecutor.execute()`` call.

    Attributes:
        character: The character ID that produced this response.
        text: The final spoken text produced by the character.
        voice_mode: The voice mode selected for this response (lowercased
            enum name, e.g. ``"working"``, ``"warm_baseline"``).
        tool_calls_made: How many tool-call iterations occurred during this
            execution (useful for observability and circuit-breaker checks).
        handoff_signal: If the character called ``request_handoff``, the parsed
            arguments dict is stored here.  ``None`` otherwise.
    """

    character: str
    text: str
    voice_mode: Optional[str]
    tool_calls_made: int = 0
    handoff_signal: Optional[Dict[str, Any]] = field(default=None)

    def to_dict(self) -> dict:
        """Serialise to a JSON-compatible dictionary."""
        return {
            "character": self.character,
            "text": self.text,
            "voice_mode": self.voice_mode,
            "tool_calls_made": self.tool_calls_made,
            "handoff_signal": self.handoff_signal,
        }


class CharacterExecutor:
    """
    Executes a single character turn: builds messages, runs the tool loop,
    and returns a ``CharacterResponse``.

    The executor is intentionally stateless — it does not modify
    ``ConversationContext.history``; the caller decides whether and how to
    persist the response.

    Interception of ``request_handoff``::

        If the LLM includes a ``request_handoff`` tool call in its response,
        the executor:

        1. Parses the arguments and stores them in ``CharacterResponse.handoff_signal``.
        2. Does NOT add a tool-result message for that call (the tool is a
           signal to the orchestrator, not a real side-effecting action).
        3. Logs the decision with ``accepted=True``.

        A second ``request_handoff`` in the same turn is logged with
        ``accepted=False, rejected_reason="FR2.4 — one handoff per turn"``
        and silently ignored.

    Args:
        llm_integration: LLM client (``LLMIntegration`` instance or compatible).
        character_system: Character system for voice mode selection.
        tool_system: Tool system for executing tool calls.
        story_engine: Story engine for ``on_tool_executed`` events.
        max_tool_calls: Maximum tool-call iterations before the circuit
            breaker fires (default: 5).
    """

    def __init__(
        self,
        llm_integration,
        character_system,
        tool_system,
        story_engine,
        max_tool_calls: int = 5,
    ):
        self.llm = llm_integration
        self.character_system = character_system
        self.tool_system = tool_system
        self.story_engine = story_engine
        self.max_tool_calls = max_tool_calls

    async def execute(
        self,
        character: str,
        task_description: str,
        context: ConversationContext,
        session_id: str,
        user_id: str,
        system_prompt_override: Optional[str] = None,
        history_window: int = 4,
    ) -> CharacterResponse:
        """
        Run the LLM + tool loop for *character* on *task_description*.

        Args:
            character: Character ID (e.g. ``"delilah"``, ``"hank"``).
            task_description: The task the character should respond to.
            context: Current conversation context (read-only within this method).
            session_id: Current session identifier.
            user_id: Current user identifier.
            system_prompt_override: If provided, replaces the system prompt
                that would otherwise be generated by the character system.
            history_window: How many recent history messages to include
                (default: 4 = last 2 turns).

        Returns:
            A ``CharacterResponse`` with the final text, voice mode, tool call
            count, and any ``request_handoff`` signal.
        """
        # --- 1. Select voice mode ---
        voice_mode: Optional[str] = None
        voice_mode_selection = self.character_system.select_voice_mode(
            character, task_description, context.metadata
        )
        if voice_mode_selection:
            voice_mode = voice_mode_selection.mode.name.lower()

        logger.info(
            "CharacterExecutor: starting execution for '%s' (session=%s, task=%r, voice_mode=%s)",
            character,
            session_id,
            task_description[:60],
            voice_mode,
        )

        # --- 2. Build system prompt ---
        if system_prompt_override is not None:
            system_prompt = system_prompt_override
        else:
            system_prompt = self._build_character_system_prompt(
                character, task_description, context
            )

        # --- 3. Prepare initial messages ---
        messages: List[Dict[str, Any]] = [
            {"role": "system", "content": system_prompt}
        ]
        for msg in context.history[-history_window:]:
            messages.append({"role": msg.role, "content": msg.content})
        messages.append({"role": "user", "content": task_description})

        # --- 4. Get tools ---
        from tools.tool_base import ToolContext

        tools = (
            self.tool_system.get_openai_functions()
            if self.tool_system.list_tools()
            else None
        )

        # --- 5. LLM + tool call loop ---
        llm_response = self.llm.generate_response(
            messages=messages,
            temperature=0.7,
            tools=tools,
        )

        tool_call_count = 0
        handoff_signal: Optional[Dict[str, Any]] = None
        handoff_accepted_this_turn = False

        while llm_response.get("tool_calls") and tool_call_count < self.max_tool_calls:
            tool_call_count += 1
            logger.debug(
                "CharacterExecutor: %s processing tool call %d/%d",
                character,
                tool_call_count,
                self.max_tool_calls,
            )

            tool_results = []
            for tool_call in llm_response["tool_calls"]:
                tool_name = tool_call["function"]["name"]

                # --- Intercept request_handoff ---
                if tool_name == _HANDOFF_TOOL_NAME:
                    if not handoff_accepted_this_turn:
                        try:
                            signal = json.loads(tool_call["function"]["arguments"])
                        except (json.JSONDecodeError, TypeError):
                            signal = {}
                        handoff_signal = signal
                        handoff_accepted_this_turn = True
                        logger.info(
                            "CharacterExecutor: %s called %s — accepted=True, to=%s",
                            character,
                            _HANDOFF_TOOL_NAME,
                            signal.get("to_character"),
                        )
                    else:
                        logger.warning(
                            "CharacterExecutor: %s called %s again in same turn — "
                            "accepted=False, rejected_reason='FR2.4 — one handoff per turn'",
                            character,
                            _HANDOFF_TOOL_NAME,
                        )
                    # Do NOT add a tool result for this call — it is a signal only.
                    continue

                # --- Execute regular tool ---
                try:
                    arguments = json.loads(tool_call["function"]["arguments"])
                except (json.JSONDecodeError, TypeError):
                    arguments = {}

                tool_context = ToolContext(
                    user_id=user_id,
                    session_id=session_id,
                    character_id=character,
                    metadata=context.metadata,
                )

                result = await self.tool_system.execute_tool(
                    tool_name, tool_context, arguments
                )
                self.story_engine.on_tool_executed(user_id, tool_name)

                tool_results.append(
                    {
                        "tool_call_id": tool_call["id"],
                        "role": "tool",
                        "name": tool_name,
                        "content": result.message,
                    }
                )

            # Append assistant turn + tool results, then get next LLM response.
            # Build the assistant message carefully: only include real tool calls
            # (exclude the intercepted request_handoff so the LLM doesn't see a
            # dangling tool call without a corresponding result).
            real_tool_calls = [
                tc
                for tc in llm_response["tool_calls"]
                if tc["function"]["name"] != _HANDOFF_TOOL_NAME
            ]

            if real_tool_calls or llm_response.get("content"):
                assistant_msg: Dict[str, Any] = {
                    "role": "assistant",
                    "content": llm_response.get("content") or "",
                }
                if real_tool_calls:
                    assistant_msg["tool_calls"] = real_tool_calls
                messages.append(assistant_msg)

                for tool_result in tool_results:
                    messages.append(tool_result)

                # Only call LLM again if there were real (non-handoff) tool results
                if tool_results:
                    llm_response = self.llm.generate_response(
                        messages=messages,
                        temperature=0.7,
                        tools=tools,
                    )
                else:
                    # Handoff-only turn — no need for another LLM round-trip
                    break
            else:
                break

        # --- 6. Extract final text ---
        text = llm_response.get("content", "") or ""
        if not text:
            text = "Done."

        logger.info(
            "CharacterExecutor: %s completed (%d chars, %d tool calls, handoff=%s)",
            character,
            len(text),
            tool_call_count,
            handoff_signal is not None,
        )

        return CharacterResponse(
            character=character,
            text=text,
            voice_mode=voice_mode,
            tool_calls_made=tool_call_count,
            handoff_signal=handoff_signal,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_character_system_prompt(
        self,
        character: str,
        task_description: str,
        context: ConversationContext,
    ) -> str:
        """
        Build a character system prompt via ``CharacterSystem``.

        Mirrors the logic in ``ConversationManager._build_system_prompt()``
        without the deferred-task hint injection (which is handled by the
        orchestrator layer for Phase 5.1).
        """
        voice_mode_selection = self.character_system.select_voice_mode(
            character, task_description, context.metadata
        )
        if voice_mode_selection:
            return self.character_system.build_system_prompt(
                character, voice_mode_selection.mode
            )
        return self.character_system.build_system_prompt(character)
